name: Code Quality

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-quality:
    name: Lint & test source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '15'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ./api/node_modules
          key: ${{ runner.OS }}-project-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-project-${{ env.cache-name }}-
            ${{ runner.OS }}-project-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test
